#!/usr/bin/env python3
"""Build the versioned lexicon (lexicon.md): a single index of EVERY name across the
corpus — Unspun entities, logic/gates/processes, Fête atoms/outcomes/backbone/axes,
value types & enums, and the ID-prefix registry. Generated; regenerate, don't hand-edit.

Usage:  python3 docs/graph/build_lexicon.py
"""
import json, re, os, yaml
BASE=os.path.dirname(os.path.abspath(__file__))
KG=json.load(open(os.path.join(BASE,'kg.json')))
FET=json.load(open(os.path.join(BASE,'..','reconciliation','fete-graph.json')))
KERN=yaml.safe_load(open(os.path.join(BASE,'..','data-model','catalog','00-kernel.yaml')))
VER=KG['meta']['version']

# glosses from the spec glossary (Unspun) ----------------------------------
GLOSS={}
for ln in open(os.path.join(BASE,'..','spec','glossary.md')):
    if ln.startswith('| ') and '`' in ln and '---' not in ln:
        c=[x.strip() for x in ln.strip().strip('|').split('|')]
        if len(c)>=4:
            nm=re.sub(r'\(.*?\)','',re.sub(r'\*.*','',c[0])).replace('`','').strip()
            if nm and nm!='Object': GLOSS[nm]=c[3]
GLOSS.update({'Atom':'A Fête atom as a control-plane process template (T01-T78).',
 'Outcome':'A received-experience line R1-R15 composing the brand promise.',
 'AtomRealization':'Runtime link: which objects realized which atom for an event (consent-gated).',
 'SensoryCue':'A sensory transition (music/light/scent/motion) paired to a beat (T38).',
 'ChildFlowStation':'A designed-pull station that moves children without instruction (T36/T54).',
 'GuestFamily':'The invited household unit (parents, children+ages, contacts, address, satisfaction).'})

CTX_LABEL={'c1':'Parties & Consent','c2':'Taste & Creative','c3':'Supply','c4':'Commercial & Finance',
 'c5':'Event Design','c6':'Production & Logistics','c7':'Risk & Resilience','c8':'Communication & Relationship',
 'c9':'Acquisition & Distribution','c10':'Operations & Team','c11':'Safety & Compliance','c12':'Platform & Governance',
 'dyn':'Dynamic Layer','ai':'AI Enablement'}
LENS={'G1':'Stage vs Back-of-house','G2':'Taste vs Logistics','G3':'Reversible vs Brand-destroying',
 'G4':'Information artifact','G5':'Asset compounding','G6':'Sensory channel','G7':'Cost-driver'}
SKILL={'TST':'taste','LOG':'logistics','NEG':'negotiation','CRF':'craft','CAR':'care/relationship',
 'ANL':'analysis/inference','COM':'communication/copy','OPS':'operations'}
QUAD={'AUTO':'agent operates','AUG-HITL':'agent drafts, human approves',
 'HUMAN-AI':'human leads live, agent scaffolds','HUMAN':'human only, AI out of customer loop'}

ents=[n for n in KG['nodes'] if n['kind']=='entity']
logic=[n for n in KG['nodes'] if n['kind'] in ('state_machine','invariant','process','logic','plane','ethos')]
atoms=sorted([n for n in FET['nodes'] if n['kind']=='atom'],key=lambda x:x['id'])
outs=sorted([n for n in FET['nodes'] if n['kind']=='outcome'],key=lambda x:int(x['id'][1:]))
ws=sorted([n for n in FET['nodes'] if n['kind']=='workstream'],key=lambda x:x['id'])
arcs=sorted([n for n in FET['nodes'] if n['kind']=='arc'],key=lambda x:x['id'])

L=[f'# Unspun — Master Lexicon · v{VER}','',
 '> A separate, versioned index of **every name** in the corpus. Generated by '
 '`build_lexicon.py` from `kg.json`, `fete-graph.json`, and the kernel — regenerate, don\'t hand-edit.',
 f'> Tracks model v{VER}. Sections: Unspun entities · logic · Fête atoms · outcomes · '
 'backbone · axes · value types & enums · ID-prefix registry.','',
 '## Version history','- `v2.0` — full corpus incl. merge bridge.',
 '- `v2.1` — GuestFamily replaces GuestParty.','',
 f'## 1. Unspun entities ({len(ents)})  — `name` · prefix · archetype · context','',
 '| Term | Prefix | Arch | Ctx | Gloss |','|---|---|---|---|---|']
for n in sorted(ents,key=lambda x:x['id']):
    L.append(f"| {n['id']} | `{n.get('pk') or ''}` | {n.get('archetype') or ''} | "
             f"{n.get('context') or ''} | {GLOSS.get(n['id'],'')} |")

L+=['',f'## 2. Logic — gates · processes · state machines · planes · ethos ({len(logic)})','',
 '| Term | Kind | Gloss |','|---|---|---|']
for n in sorted(logic,key=lambda x:(x['kind'],x['id'])):
    L.append(f"| {n['id']} | {n['kind']} | {n.get('label','') or ''} |")

L+=['',f'## 3. Fête atoms ({len(atoms)})  — T01-T78 · quadrant · primary skill','',
 '| Atom | Quadrant | Skill | Name |','|---|---|---|---|']
for a in atoms:
    L.append(f"| {a['id']} | {a['quadrant']} | {a['skill']} | {a['name']} |")

L+=['',f'## 4. Outcomes ({len(outs)})  — R1-R15','','| Code | Received experience |','|---|---|']
for o in outs: L.append(f"| {o['id']} | {o.get('label','')} |")

L+=['','## 5. Backbone — arcs · phases · workstreams','',
 '**Arcs:** '+' · '.join(f"{a['id'].split(':')[1]} {a.get('label','')}" for a in arcs),'',
 '**Phases:** P01–P15 (P01–03 Arc A · P04–08 B · P09–11 C · P12–13 D · P14–15 E)','',
 '**Workstreams:** '+' · '.join(f"{w['id']} {w.get('label','')} [{w.get('wstype','')}]" for w in ws)]

L+=['','## 6. Axes — skills · quadrants · lenses','',
 '**Skills:** '+' · '.join(f"{k} ({v})" for k,v in SKILL.items()),'',
 '**Quadrants:** '+' · '.join(f"{k} ({v})" for k,v in QUAD.items()),'',
 '**Lenses:** '+' · '.join(f"{k} {v}" for k,v in LENS.items())]

vt=list((KERN.get('value_types') or {}).keys()); en=list((KERN.get('enums') or {}).keys())
L+=['','## 7. Value types & enums (kernel)','',
 '**Value types:** '+' · '.join(f"`{v}`" for v in vt),'',
 f'**Enums ({len(en)}):** '+' · '.join(f"`{e}`" for e in en),
 '**+ enum** `automation_quadrant` (merge bridge).']

# ID-prefix registry (uniqueness check)
pref={}
for n in ents:
    p=n.get('pk')
    if p: pref.setdefault(p,[]).append(n['id'])
dups={p:v for p,v in pref.items() if len(v)>1}
L+=['',f'## 8. ID-prefix registry ({len(pref)} prefixes)','',
 ('**Collisions:** '+'; '.join(f"{p}→{v}" for p,v in dups.items())) if dups else '_No prefix collisions._','',
 '| Prefix | Entity |','|---|---|']
for p in sorted(pref): L.append(f"| `{p}` | {', '.join(sorted(pref[p]))} |")

open(os.path.join(BASE,'lexicon.md'),'w').write('\n'.join(L)+'\n')
total=len(ents)+len(logic)+len(atoms)+len(outs)+len(ws)+len(arcs)+len(vt)+len(en)
print(f"lexicon v{VER}: entities={len(ents)} logic={len(logic)} atoms={len(atoms)} "
      f"outcomes={len(outs)} prefixes={len(pref)} dups={list(dups)} ~total_terms={total}")
